version: "3.8"

services:
  xiaomi_token_extractor:
    image: techblog/xiaomi_token_extractor:latest
    container_name: xiaomi_token_extractor
    restart: always
    labels:
      - "com.ouroboros.enable=true"
    environment:
      - XIA_USER=ilinca_sebastian@yahoo.com #Xiaomi UserId or Email
      - XIA_PASS=sebisebi14 #Xiaomi Password
      - XIA_SRV=  #Optional: ["cn", "de", "us", "ru", "tw", "sg", "in", "i2"]
    ports:
      - "8080:8080"