version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    ports:
      - "1883:1883" # Maparea portului MQTT
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf # Legarea fișierului de configurare
    restart: always
